### ISSUE TITLE
Multiverse

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/OgarUL-Plugin-Library#11]
Multiverse commands work fine.. just when we try to play..
http://prntscr.com/bewoue

**Comment by Megabyte918** [comment]
disable tampermonkey and try again

**Comment by raphyjb** [comment]
Didnt do nothing still same!!!!!!! Its the game... multiverse the problem

**Comment by LegitSoulja** [comment]
@raphyjb Multiverse is not a plugin.

**Comment by raphyjb** [comment]
._. u told me to post it here

**Comment by LegitSoulja** [comment]
No, I told you too post here about a plugin which was givememinions, or superminions it was. I didn't say multiverse.

**Comment by raphyjb** [comment]
oh ok sry
