### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/OgarUL-Plugin-Library#15]
How do you verify if other people can access my server in "http://stats.ogarul.tk/" ?

**Comment by Andrews54757** [comment]
1. all game server ports must be port forwarded
2. server name is not default
3. stats port also needs to be forwarded

**Comment by GhostShot3** [comment]
@Andrews54757 http://stats.ogarul.tk/ server name "skrubs" look for me

**Comment by LegitSoulja** [comment]
If you see your server on the client fetch list then you are good. You can also use a open port checker tool just to make sure. If you don't see your server you can recreate it with ease by using this command 

* stats delete

You can restart to take immediate effect, or wait a minute until it refreshes your info which will recreate your server on the list.

You will also see a message saying your server has been added to the list with a rules link you must follow
