### ISSUE TITLE
Statistics Plugin Error

### ISSUE THREAD

**Issue by fayizan** [AJS-development/OgarUL-Plugin-Library#16]
@LegitSoulja It is showing No network connectivity,plugin is disabled but My game is working good like before ,I used stats overide and verified the config of plugin,please solve this

![screenshot_2016-06-22-05-24-49](https://cloud.githubusercontent.com/assets/19163419/16250309/fef585c2-3839-11e6-8f57-eb24a66b54b6.png)

**Comment by LegitSoulja** [comment]
@fayizan I just did a hot fix. Restart the server and let it re-update. If the problem persist please let me know. Otherwise close this issue. Thanks

**Comment by LegitSoulja** [comment]
You might have to run the command **plugin update Statistics** to bypass that network error for fix

**Comment by fayizan** [comment]
I tried `plugin update Statistics` but this error shows up
![screenshot_2016-06-22-10-30-51](https://cloud.githubusercontent.com/assets/19163419/16255553/77b04492-3868-11e6-9ce3-fdf0f3740c8a.png)

Then I deleted the statistics plugin fully and fresh installed it and now its working

![screenshot_2016-06-22-10-50-17](https://cloud.githubusercontent.com/assets/19163419/16255571/a21a4c1e-3868-11e6-8f8b-419e5e28bdf9.png)
