### ISSUE TITLE
Statistics Problem? 

### ISSUE THREAD

**Issue by Insane-Agar** [AJS-development/OgarUL-Plugin-Library#17]
Ok, so in the plugin, "Statistics" there is a feature that I thought would redirect to my custom client. However it did nothing when I tested it. The config value is "clientlink" Am I misunderstanding the use of the client link feature? Or is it just not working?

**Comment by Insane-Agar** [comment]
Also, if I can redirect people to my custom client, it has the potential to have a login system ;)

**Comment by LegitSoulja** [comment]
Client link was deprecated, it no longer exist.

**Comment by Insane-Agar** [comment]
Is there anyway that I could redirect the players joining my server to a custom client? Would I have to make my own plugin?

**Comment by LegitSoulja** [comment]
@Insane-Agar there's no way possible. Unless you use the ads plugin, and make some javascript that detects another client, and redirect to yours.

**Comment by Insane-Agar** [comment]
Thanks for your help, I'll ask my developers to work on it.
