### ISSUE TITLE
Error in my server

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/OgarUL-Plugin-Library#18]
I try to create my server to the plugin " Statistics " plus it does not appear in " http://stats.ogarul.tk/ " already deactivated firewall, windows defender, put a fixed ip, open all ports tried everything and it continues not appearing on the list.

**Comment by LegitSoulja** [comment]
Update coming soon for fix

**Comment by GhostShot3** [comment]
@LegitSoulja Is error in plugin ?

**Comment by LegitSoulja** [comment]
@GhostShot3 no

**Comment by GhostShot3** [comment]
@LegitSoulja " Update coming soon for fix  "
