### ISSUE TITLE
Statistics Showing NaN in Server Ip

### ISSUE THREAD

**Issue by fayizan** [AJS-development/OgarUL-Plugin-Library#19]
@LegitSoulja something went wrong,Just here to notify you

![screenshots_2016-06-30-16-52-30](https://cloud.githubusercontent.com/assets/19163419/16486703/07a61c58-3ee4-11e6-9a6f-2c1d4c5e0a74.png)

**Comment by fayizan** [comment]
It got fixed by itself

**Comment by GhostShot3** [comment]
@fayizan I have the same how you fix ?

**Comment by LegitSoulja** [comment]
@GhostShot3 I should've added a ip check :/....

Sometimes, (which never happened to me), your ip sometimes won't be resolved, therefor return back as a NaN, which duh, an ip won't be a number?

But anyways, if it returns as that, just set usevpsip to 0 and set customip to your computer ip. 

**Note**: Do not add no port, nor protocol to customip when using.

**Comment by LegitSoulja** [comment]
Statistics Configuration

**Comment by LegitSoulja** [comment]
Google (What's my ip), or go to http://ipchicken.com for your computer/network local ip.

**Comment by GhostShot3** [comment]
@LegitSoulja Statistics never work into me server,i opened all ports change teh conifg multiples times,but never work idk what are doing.

**Comment by GhostShot3** [comment]
@LegitSoulja Now it showing NaN port http://prntscr.com/bop3rf

**Comment by GhostShot3** [comment]
@LegitSoulja Can you help me with team viewer ?

**Comment by NatsuTheGreat** [comment]
> which duh, an ip won't be a number?

In JavaScript NaN is considered to be a number, which is weird because NaN stands for Not a Number. :/

**Comment by LegitSoulja** [comment]
@NatsuTheGreat but the ip is a string method :/

**Comment by LegitSoulja** [comment]
@GhostShot3 , no I don't use teamviewer. 

You shouldn't get a NaN if you set your ip manually in the statistics configurations.

**Comment by GhostShot3** [comment]
@NatsuTheGreat  What IP i put ?

**Comment by LegitSoulja** [comment]
@GhostShot3 I have already told you. Natsu doesn't know about this so why would you ask him?

**Comment by NatsuTheGreat** [comment]
>but the ip is a string method :/

Ghost, check that your IP is inside "" or ''.

>Mainly your IP your friends will connect to.

Use your server IP I am pretty sure, and set ```usevpsip``` to 0

**Comment by LegitSoulja** [comment]
How can he check if the ip is inside "" and '' when it's neither haha. That's why I told him to add his ip to the config, because the true ip of the computer wasn't returning back :/.

Set usevpsip = 0
Set customip = "your_ip"

Do not add no ports to custom ip. Search google for your ip. Done... Now you don't have to worry about getting a NaN error which is weird and random.
