### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Hunter2890** [AJS-development/OgarUL-Plugin-Library#21]
Since you clearly are good at coding would you be able to make a macro to split instead of just space like make it x for player to split and D for minion to split and a extra zoom this would be greatly appreciated thanks!

**Comment by LegitSoulja** [comment]
Extra zoom is not tolerated. Which brings an unfair advantage to the game.

Also the keybinds you said is kindof weird.

**Comment by Megabyte918** [comment]
that would be cool actually "custom macros"
