### ISSUE TITLE
help needed with plugins

### ISSUE THREAD

**Issue by Yamanourani** [AJS-development/OgarUL-Plugin-Library#22]
when ever i try to iinstall a plugin it tells me this 
>plugin install account-rewards
>[Console] That plugin does not exist. Do plugin available to see available plugins and plugin search to search plugins!

Please help.

**Comment by Yamanourani** [comment]
im trying to install ipBots never works :((

**Comment by LegitSoulja** [comment]
@Yamanourani Plugin names have to be spelled specifically. 

You can do
> plugin search rewards

then install
> plugin install AccountRewards

**P.S**: IPBOTS doesn't exist yet.
