### ISSUE TITLE
Ogar console error

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/OgarUL-Plugin-Library#26]
I write the password but when I give some comand example "kill all" it needs password again.

**Comment by GhostShot3** [comment]
@LegitSoulja lel ?

**Comment by LegitSoulja** [comment]
You are annoying, stop making issues about this cause this is not even an issue.

**Comment by GhostShot3** [comment]
@LegitSoulja I need to fix,sorry for duplicate

**Comment by LegitSoulja** [comment]
I can't fix whats not broken kiddo.

**Comment by GhostShot3** [comment]
@LegitSoulja okay I'm not the console so ...

**Comment by LegitSoulja** [comment]
Nobody never told you to use pm2. pm2 doesn't even work, therefor if you are having problems, then thats your fault. Nobody told you to use pm2. Good day now.
