### ISSUE TITLE
0/0 Slot

### ISSUE THREAD

**Issue by xWourFo** [AJS-development/OgarUL-Plugin-Library#27]
When my server is started it can be seen in the list but there are 0 player slots (0/0).What do i have to do to fix it? (I used the statistics plugin)

**Comment by GhostShot3** [comment]
@xWourFo Are you sure that your server is running 100%?

**Comment by LegitSoulja** [comment]
Because.. There's 0 players, and 0 bots (At the time). Updates every minute.

**Comment by SharkFinPro** [comment]
This should be closed
