### ISSUE TITLE
Servidor Br

### ISSUE THREAD

**Issue by danielgft** [AJS-development/OgarUL-Plugin-Library#28]
Servidor Pica

**Comment by GhostShot3** [comment]
??? wut

**Comment by LegitSoulja** [comment]
Good thing I know a little bit about Portuguese from my British friends

escolher um servidor?

**Comment by NatsuTheGreat** [comment]
Portuguese from your British friends?

**Comment by LegitSoulja** [comment]
Yea, some of my British friends speaked Portuguese, and I kindof understood it a little bit because I was always around it. You'll eventually understand the language a little bit of you be around them for years.
