### ISSUE TITLE
About plugins.

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/OgarUL-Plugin-Library#29]
In `OgarConsole` does not work `Shortcuts` plugin commands, commands like `ka sp` etc but in cmd works.

**Comment by LegitSoulja** [comment]
You can't use it with plugin commands. Can you like not create these spam issues? Thanks. No more issues about OgarConsole now.

**Comment by GhostShot3** [comment]
Ok @LegitSoulja

**Comment by GhostShot3** [comment]
@LegitSoulja You want me to stop creating issues?
