### ISSUE TITLE
Ipbots

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/OgarUL-Plugin-Library#32]
The supermass doesnt work.. im trying to get them to work but.. they keep spawning 300 mass (players spawn with that mass) and i tryed to put it 10 mass, but they aint going for 10mass but 300.. :/
The plugin is better then exepted <3
Doing a great job @LegitSoulja

**Comment by LegitSoulja** [comment]
Nah, this one sucks. Only wished if  I had made the store(shops).

**Comment by LegitSoulja** [comment]
@raphyjb SuperMass does work, but like I told someone already, the mass cannot be smaller than the player start mass.

**Comment by raphyjb** [comment]
How do i have a plugin to get poeple to spawn with that much mass? Huh?! :P Could u do it?

**Comment by LegitSoulja** [comment]
@raphyjb 

In your main game config, set the player start mass too 1

Install this plugin
[MassStart.zip](https://github.com/AJS-development/OgarUL-Plugin-Library/files/392145/MassStart.zip)

Change playerStartMass in the plugin MassStart config
.

**Comment by LegitSoulja** [comment]
@Megabyte918 Close...
