### ISSUE TITLE
helpp needed 

### ISSUE THREAD

**Issue by Yamanourani** [AJS-development/OgarUL-Plugin-Library#33]
i cant install super minions plugin
tells me it doesnt exist

**Comment by LegitSoulja** [comment]
SuperMinions (Case Sensitive)

**Comment by GhostShot3** [comment]
@Yamanourani Go to console and type `plugin istall super minions`

**Comment by LegitSoulja** [comment]
@GhostShot3 it is **SuperMinions** not **super-minions** nor **Super-Minions**

**Comment by GhostShot3** [comment]
@LegitSoulja thx .
