### ISSUE TITLE
Cant load plugin

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/OgarUL-Plugin-Library#36]
![dddsfsd](https://cloud.githubusercontent.com/assets/18537420/17336280/d830cb5a-58b3-11e6-8256-b5fb0424e4fb.png)

**Comment by LegitSoulja** [comment]
make a file config.ini inside the essentials commands plugin folder.

The plugin required and config, but didn't have one attached.

**Comment by SharkFinPro** [comment]
should this be closed?
