### ISSUE TITLE
Client Bugs

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/OgarUL-Plugin-Library#4]

**Comment by LegitSoulja** [comment]
When you enlarge the map via command, it glitches out when you try to continue to go to the enlarged part of the map.

**Comment by LegitSoulja** [comment]
plugin install Client doesnt install the client.

**Comment by Andrews54757** [comment]
The plugin is only made so the client can be implemented with ogarul. But, the client files are not there because of moneyclip

**Comment by LegitSoulja** [comment]
Okay. I wasnt for sure. Thats why I posted #538 so people can use that client there until you get your site up
