### ISSUE TITLE
I Need Help With the Statistics Plugin

### ISSUE THREAD

**Issue by ZlkGamingYT** [AJS-development/OgarUL-Plugin-Library#41]
Ok so basically i just need help with this, PLEASE NOTE. SERVER STAT PORT HAS TO BE OPEN FOR THIS TO WORK!. DO NOT USE LOCALHOST INFORMATION// What do you do open your server stat port?

**Comment by LegitSoulja** [comment]
Yes. When using statistics that means you are allowing your server to be public for other people to join. For this to work, in order for me to determine if your server is online or not you will need to port forward your server start port by default is 88. You will have to open that port, and also your game server port 443 which then players will be able to join the game, and also able to see if your server is online or not.

Everything is self explanatory.

**Comment by ZlkGamingYT** [comment]
Ok thank you, all i need to do is wait for a friend to be online to test my server is AMERICA-NO LAG
and then i can figure out if i have any problems. Thank you

**Comment by LegitSoulja** [comment]
@ZlkGamingYT You could also use a open port checker to test your ports to make sure they are open. As of right now, I don't see your server on this list at all.

**Comment by LegitSoulja** [comment]
Well yes, looking back at the data your server is on the list but either ports are down, or the server isn't currently running right now. 

You really don't need noone to test. Eventually some random person will join your server when they see it.

**Comment by ZlkGamingYT** [comment]
ive  been trying to open my ports but i dont know how

IVE LITERALLY WATCHED SO MANY VIDS ;(

**Comment by LegitSoulja** [comment]
It's really easy and simple... You just need to know what you're doing. And understand what you're looking at.

**Comment by ZlkGamingYT** [comment]
yeah i know i entered the numbers and all, but it goes to completely different looking site than everyone elses

**Comment by ZlkGamingYT** [comment]
my server literally perfect but thats all i need ;(

**Comment by LegitSoulja** [comment]
A different site? 

I think you mean your router configurations. Yes, everyone doesn't have the same router, and or server equipment. You'll have to search google based on your router onto knowing how to port forward.

**Comment by LegitSoulja** [comment]
But is there anything else you need help with? If not close this issue please.

I, nor we cannot help you with port forwarding. That's knowledge that you'll need to know and understand. Google will be your friend with this one. 

You can also check your router home page for help, or call your ISP. I doubt they wouldn't help if you ask. Good luck.

**Comment by ZlkGamingYT** [comment]
ok thanks mans ill try my best
