### ISSUE TITLE
How to run ?

### ISSUE THREAD

**Issue by dinhduynhat** [AJS-development/OgarUL-Plugin-Library#42]
![image](https://cloud.githubusercontent.com/assets/20450856/18191425/626f89d4-70f4-11e6-87bb-716eda7f883f.png)
![image](https://cloud.githubusercontent.com/assets/20450856/18191441/7c0c091c-70f4-11e6-8c6a-822a2645157e.png)

**Comment by LegitSoulja** [comment]
You don't run plugins. Plugins are used with OgarUnlimited, and can only be read by OgarUnlimited, and cannot be executed which will turn out with no results whatsoever..

To use plugins, simply download the folder(Plugin) and put it into the plugins folder of OgarUnlimited.

Or, use simple installation commands
> plugin search [keyword/filter]
###### Then to install, for example with the plugin you are using now
> plugin install Auth

**Plugin names are case sensitive when using the _plugin install method_**.

**Comment by dinhduynhat** [comment]
are you have file agario findserver ?

**Comment by LegitSoulja** [comment]
Come again?
