### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by iIronicGameryt** [AJS-development/OgarUL-Plugin-Library#7]
Could you make a agar chat on the bottom left for the server it would be amazing! :D thanks.

**Comment by LegitSoulja** [comment]
@iIronicGameryt I was going to, but haven't got to it yet. soon

**Comment by iIronicGameryt** [comment]
yes!! :D cant wait!! i have quite alot of people playing on my servers usually! :) so i added chotovod while it comes! :)

**Comment by SharkFinPro** [comment]
This should be closed since there is one...
