### ISSUE TITLE
Get Config?

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/OgarUL-Plugin-Library#8]
@Andrews54757 umm, I cannot figure out why the config is not working.

```
this.config = {
    test: 5,
    testa: 10
};

this.configfile = 'config.ini';

this.init = function(gameServer, config){

    this.config = config;
    
    this.config.test // output 5 instead of  10
    this.config.testa // output 10 instead of 0

};

module.exports = this;
```

### Config file
test = 10
testa = 0

> Config from the file is not updating.. What am I doing wrong?

**Comment by LegitSoulja** [comment]
Can I just call ini from modules and parse them? Then set the values

**Comment by Andrews54757** [comment]
your config file is wrong, instead of using \:, you have to use =

**Comment by LegitSoulja** [comment]
@Andrews54757 mybad, i didnt mean to put that. It is =

**Comment by Andrews54757** [comment]
send me your plugin

**Comment by LegitSoulja** [comment]
@Andrews54757 I think i figured it out. It was being weird until I changed some stuff around.

**Comment by LegitSoulja** [comment]
@Andrews54757 Ok, so im rewriting givememinions better because I wasnt never entending it to be a plugin, but it became, and I just had threw it togehter. 

So, I'm coming down with some problems that I dont think I can solve. Maybe you can take a look at it? I left comments and all to what exactly what. 
> Mainly, so for example a client gets minions, and there pID is then stored into an array, then on the next go around it checks that array and make sure that pID hasnt went twice. Well I thought I found out my issue with having no problems with 1 person, but I was wrong. Now im stuck and clueless on how I can get this working properly.

[GiveMeMinions.zip](https://github.com/AJS-development/OgarUL-Plugin-Library/files/267418/GiveMeMinions.zip)

**Comment by LegitSoulja** [comment]
You'll see what I mean when you test it out once. It works perfect the first and second time, then I just don't after that.

**Comment by LegitSoulja** [comment]
update..

It's almost getting there @Andrews54757 :/

[GiveMeMinions.zip](https://github.com/AJS-development/OgarUL-Plugin-Library/files/268685/GiveMeMinions.zip)

**Comment by LegitSoulja** [comment]
Im going to remove the command use too btw, and implement it correctly without executing the command but gameServer.addbot.minion way instead.

**Comment by Andrews54757** [comment]
?

**Comment by Andrews54757** [comment]
also, your ogarconsole doesnt work anymore for ogar ul

**Comment by LegitSoulja** [comment]
@Andrews54757 I know why. I actually updated the oldindex.js, thats why.

**Comment by LegitSoulja** [comment]
@Andrews54757 Fixed it.. And did you download and read what I said im having problems with?

**Comment by Andrews54757** [comment]
I dont understand your code. there are some really strange parts such as tlast.length = 0

**Comment by LegitSoulja** [comment]
@Andrews54757 That's a way I found to reset the array.

**Comment by Andrews54757** [comment]
no, that doesnt reset it. .length is not setable. To reset it. use tlast = [];

**Comment by Andrews54757** [comment]
Whats the difference between tlast and last

**Comment by LegitSoulja** [comment]
tlast is set, and only used when removing all the minions with the store pID, then it resets.

last stores pID of the users that got minions, and then again checks to see if a user got minions twice, if he did then it ignores to give that pID minions then remove the pID from last

**Comment by Andrews54757** [comment]
Il rewrite it

**Comment by LegitSoulja** [comment]
@Andrews54757 ok, maybe you can write it better.

**Comment by Andrews54757** [comment]
sorry but it is kinda horribly coded. So, you want the plugin to give a certain amount of minions  every second? and not repeat?

**Comment by Andrews54757** [comment]
see my progress here https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/givememinionstwo

**Comment by LegitSoulja** [comment]
@Andrews54757 Yea i know, cause i just threw it together

Well theres a config if you read and understand.

every switchIntervalTime time, and for each setPerInterval it will repeat

Once a person gets the minions, there id is stored, and then if setPerInterval > 0 it checks to make sure the random number doesnt pick the person again who has already gotten it

when the switchIntervalTime comes again, the stored pID's will remove all minions from the pID

**Comment by Andrews54757** [comment]
wont be too hard

**Comment by LegitSoulja** [comment]
@Andrews54757 https://github.com/AJS-development/Ogar-unlimited/issues/608

he was the one requested it.

**Comment by Andrews54757** [comment]
I think I finished it here https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/givememinionstoo

**Comment by Andrews54757** [comment]
never tested it though. I also added a command

**Comment by LegitSoulja** [comment]
@Andrews54757 Ok, I will test it. Also, I made OgarConsole and actual plugin, and it should now no longer replace files, and should not be in the way of OgarUl updates :)

**Comment by Andrews54757** [comment]
Oops i forgot something

**Comment by LegitSoulja** [comment]
@Andrews54757 ok how does it work?

**Comment by LegitSoulja** [comment]
It just destroys, but it doesnt give

**Comment by Andrews54757** [comment]
@LegitSoulja I updated the plugin

**Comment by Andrews54757** [comment]
works like a charm

**Comment by Andrews54757** [comment]
i found another bug, fixing...

**Comment by LegitSoulja** [comment]
TypeError: Cannot read property 'pID' of undefined
    at Object.<anonymous> (C:\Users\LegitSoulja\Desktop\Ogar-unlimited-master\src\plugins\5ngeK8r\index.js:101:35)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

**Comment by Andrews54757** [comment]
yeah, i just fixed that

**Comment by LegitSoulja** [comment]
interval isnt updating, minions arent getting destroyed, and bots arent getting minions neither

**Comment by Andrews54757** [comment]
i fixed that as well

**Comment by Andrews54757** [comment]
dont use the raw feature. its not updating

**Comment by Andrews54757** [comment]
you have to go to editor and copy and paste

**Comment by Andrews54757** [comment]
github is being stupid

**Comment by LegitSoulja** [comment]
?
> plugin add https://raw.githubusercontent.com/AJS-development/OgarUL-Plugin-Library/master/givememinionstoo/files.txt

worked.. and the plugin is working correctly im guessing. 

You can delete mines aswell

**Comment by Andrews54757** [comment]
Here
[minions.zip](https://github.com/AJS-development/OgarUL-Plugin-Library/files/269537/minions.zip)

**Comment by Andrews54757** [comment]
github is not updated live there is a delay so that is why your version of givememinions are outdated

**Comment by LegitSoulja** [comment]
@Andrews54757 no, you grabbed givememinions from the issues, without my consent of it being an actual plugin lol. I was working on it more and gave you the new givememinions above, but i never had updated it.

But since you remade it, you can delete mines and have yours as GiveMeMinions instead.

**Comment by Andrews54757** [comment]
no, i meant that Github's raw website is slow and is not updated live. So if I make some updates now, you wont be able to see it by clicking on the raw button until like a day later

**Comment by Andrews54757** [comment]
And the plugin add command uses the raw feature

**Comment by Andrews54757** [comment]
so your version of my version is outdated because you are using the raw feature of github

**Comment by LegitSoulja** [comment]
@Andrews54757 oh gotcha

**Comment by Andrews54757** [comment]
BTW if you make ogarconsole into a plugin, it also means that you can make it have an update system. Because I made the plugin update command. To allow this to happen, you have to include a files.txt file

**Comment by LegitSoulja** [comment]
@Andrews54757 Yea i know
https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/OgarConsole-Installer

I had added a new -update command to OgarConsole for manually updates..

Im going to grab a request from package.json from here to match the versions and manually update.

I'm not planning on working on this no more in the future, Might do 1 or 2 more updates after things are working properly. I discontinued OgarConsole but, I converted it to a plugin for OgarUl use.

**Comment by LegitSoulja** [comment]
I was going to rewrite it again specificly for a plugin use, but I was able to still get it working without having to do so.

You know OgarConsole was never a plugin, it was like an addon/mod. Haha, but now plugins exist so it can be one.

**Comment by LegitSoulja** [comment]
@Andrews54757 and whats up with the oxwall problem? You said it wasnt there, I install it back again, and now its gone again. Do you want xenforo?

**Comment by Andrews54757** [comment]
@LegitSoulja I deleted it the second time as it was lagging the server. Ive decided to research other options

**Comment by LegitSoulja** [comment]
@Andrews54757 ok, well. If you ever install something on your own, ill make a mysql.sql file in forum root with your mysql information

**Comment by LegitSoulja** [comment]
@Andrews54757 ok, you should see the file now with your mysql info

**Comment by LegitSoulja** [comment]
in ogarul database, theres a servers table. That statistics plugin adds servers information there for collection btw. So dont drop it.

**Comment by Andrews54757** [comment]
@LegitSoulja Surfing around and I found this https://community.c9.io/t/devs-only-banned/5481. XtremePlaysCode got burned, no got TOASTED. Actually funny how he contradicts him self and spams. I feel bad for him that he got banned from Ogar Unlimited and C9

**Comment by LegitSoulja** [comment]
@Andrews54757 I don't feel bad for him. We all had roasted him on the issues because he was spamming, and also talking tash.

He kept bugging me to help him make fb bots, and he got mad at me and you because he couldnt be part of ajs.
